### ISSUE TITLE
Duplicate post numbering when merging discussions causes error

### ISSUE THREAD

**Issue by dsevillamartin** [FriendsOfFlarum/merge-discussions#5] opened 2019-07-29 21:46 UTC
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '292-3' for key 'posts_discussion_id_number_unique'
```

It occurs when re-numbering the posts in the new discussion.

Not sure why it only occurs sometimes. Perhaps because of the order in which posts are processed (by ID / creation date).

**Comment by rob006** [comment] 2019-09-15 17:42
This bug is pretty consistent for me - it happens always when merge will require posts renumbering (you need to merge posts older than last post in target discussion).

**Comment by rob006** [comment] 2019-09-15 17:57
I opened PR with fix: https://github.com/FriendsOfFlarum/merge-discussions/pull/7

I'm not using Laravel, so please make sure that I didn't do anything stupid. :P

**Comment by matteocontrini** [comment] 2019-10-08 21:38
It doesn't appear to be fixed: https://discuss.flarum.org/d/19460-friendsofflarum-merge-discussions/31

@rob006 any idea of what could help in debugging?

**Comment by rob006** [comment] 2019-10-08 22:29
@matteocontrini I edited some Laravel files to log (simple `file_put_contents()`) all queries before executing it, and I figure out what is happening. I have no idea how to setup proper debugging with Flarum, and Eloquent is just pure magic...

**Comment by imorland** [comment] 2020-02-08 17:20
Been spending a little time today looking into this.

So it appears this issue occurs when there are gaps in the post `number` sequence. Not sure of the cause yet, but potentially could be:

- Deleted post(s)
- Split posts from the discussion
- Something else

My first idea is to run a check for the `number` of the last post in the discussion, and if this differs from the overall count, then re-number the posts before attempting the merge.

@datitisev I know you worked on this extension, do you have any insights on these findings?

I'll continue to investigate and play around with some ideas. I'm determined to get a fix for this ASAP 😄

**Comment by imorland** [comment] 2020-02-08 18:19
Got this working, at least for our use case. #9

**Comment by imorland** [comment] 2021-12-03 17:07
Potentially addressed by https://github.com/FriendsOfFlarum/merge-discussions/pull/30 - tagged as `1.0.1`

**Closed as completed** 2022-01-04 20:39 UTC
Labels: bug
